window.PROGRESS = `
<p><b>Round 2 of the loop</b> — from scratch in <code>v2/</code>, against the pixel-level bar (<code>design/bar.md</code>). Fonts: free stand-ins (Roboto Condensed · Arimo · Roboto Mono). <b>30 Sep: piece 1 restarted at round 15</b> — 1a the hero loop (bar rules 8–12), 1b the entrance never sticking. <b>Round 17</b>: the owner judged round 16 "something weird" — the reference is light bounced off water, not objects; the loop is now a simulated water caustic (no credits). Higgsfield ≈ 2.3 credits; the plan's 200 come back with the reset offered until 1 Oct 00:00 UTC.</p>
<table><tr><th>Piece</th><th>Status</th><th>Brief</th><th>System</th><th>Craft</th><th>Latest</th></tr>
<tr><td>1 · Entrance + hero</td><td>round 18 — loading fixed; loop direction with the owner</td>
<td class="pending">R1 ✗ · R2 — · R3 ✗ · R4 ✗ · R5 (rate-limited) · R6 ✗ · R8 ✗ · R9 (rate-limited) · R10 ✗ · R12 ✓ · R15 ✗ · R17 ✗</td><td class="pending">R1 ✗ · R2 ✗ · R3 ✗ · R4 ✓ · R5 (rate-limited) · R6 ✗ · R7 ✗ · R8 ✓ · R10 ✓ · R15 ✓</td><td class="pending">R1 ✗ · R2 ✗ · R3 ✗ · R4 ✗ · R5 ✗ · R6 ✗ · R7 ✗ · R8 ✗ · R9 ✗ · R10 ✗ · R11 ✗ · R12 ✗ · R13 ✗ · R14 ✗ · R15 ✗ · R16 (owner ✗) · R17 ✗</td>
<td>Every entrance event within ±160 ms of the reference; 16/16 parallel loads clean; black from first paint on fast and phone-speed loads; fonts swap (never stall); only the entrance's scripts load first. Hero v6: a Higgsfield take of copper and steel planes and arcs, defocused in camera, gliding sideways with a focus that drifts in and out; saturation held steady (gpt-image-2.5 still animated by Seedance 1.5 with the same still as first and last frame, so it closes on itself), screened over itself mirrored and half a cycle on, tinted slate; 44% warm / 30% cool (ref 55/37), left/right thirds 36/23 (30/20); blacks shown true on the page (sRGB transfer tag). Wordmark at weight 900. Entrance scripts fetched and watched: a held script opens the page at 2.8 s, a failed one at ~25 ms.</td></tr>
<tr><td>2 · Nav + motion</td><td>done — one lean blind pass: menu timing, stagger, layout, link hover, close and hide-on-scroll at parity; its two misses (hover scramble, frosting on scroll-up) were capture artefacts, both verified working directly</td><td>—</td><td>—</td><td>R1 ✓ (verified)</td>
<td>Menu (11 sections from data.js, 0.2 s + 0.1 s stagger, MENU↔CLOSE, Escape, focus), nav clear at top / hides scrolling down / returns frosted, pill glow, hover scramble, heading decode, Lenis at the reference's settings.</td></tr>
<tr><td>3 · Home page</td><td class="pending">next session — port the overview, materials, principles, lighting and problems from the current site into v2</td><td class="pending">—</td><td class="pending">—</td><td class="pending">—</td><td>Four material textures (teak, taupe marble, white marble, brass) and two night backdrops generated.</td></tr>
<tr><td>4 · Room pages + drawings</td><td class="pending">next session — port the room pages, sheets and zoom viewer</td><td class="pending">—</td><td class="pending">—</td><td class="pending">—</td><td>From data.js, untouched.</td></tr></table>
<h3 style="font-weight:400;margin-top:32px">Gap history — piece 1</h3>
<table><tr><th>Round</th><th>Biggest gap named</th><th>Fix</th></tr>
<tr><td>R1</td><td>brief: some loads stayed black · system: condensed register missing (extract vs live site) · craft: hero one flat diagonal band</td><td>threaded dev server + fail-open page; addendum; baluster footage</td></tr>
<tr><td>R2</td><td>system: centre lines tracked −0.05em, letters touch · craft: brightest area behind the mark, room readable, grey highlights</td><td>−0.02em; centre pool, heavier blur, split-tone grade</td></tr>
<tr><td>R3</td><td>brief: the finished page paints before the entrance on first visits · system: lockup 107×191 vs 141×163 · craft: all vertical columns lit from above, bright-top/black-bottom</td><td>entrance hidden from first paint (fail-open at 5.875 s); one-line lockup at the reference's block; three layers at three angles, flattened</td></tr>
<tr><td>R4</td><td>brief: a stalled font leaves the hero's words invisible · craft: video a neutral column at the left edge over empty black; needs 4–6 warm and cool shapes across the frame</td><td>font-display swap + subset; loop v4 from glassware takes, colour-mapped copper/slate, light spread across the frame</td></tr>
<tr><td>R5</td><td>craft: the loop still reads as a room (lamp shade, window, armchair); navy lifted shadows; flat orange highlights; grain on the page</td><td>two new abstract takes, no room in them; neutral shadows, cream highlights, encode grain 3 → 1</td></tr>
<tr><td>R6</td><td>craft: loop a one-way morph with a crossfade seam, rims read as a bulb, too little cool light · system: arcs 1.6 px not hairline, wordmark untracked, 16 px text −0.022em; four live-site overrides not in the addendum</td><td>eased cycle, blur 56, second steel-blue streak; 1 px non-scaling arcs, −0.02em throughout; addendum rows for the hover glow, stand-in faces, phone burger, lockup gap</td></tr>
<tr><td>R6 brief</td><td>a blocked, 404, truncated or throwing app.js leaves the hero black for 5.9 s</td><td>fail open on any script error before the engine starts (~30 ms); reveal on the poster if the video is late</td></tr>
<tr><td>R7</td><td>craft: loop lifted and blue-hazed, a uniform smear rather than lens defocus · system: mark-to-wordmark 32 px ink to ink (29), lines close up ~7 px when the scramble ends</td><td>lockup 29 px ink to ink; entrance text unkerned; new loop from defocused-in-camera stills animated start = end</td></tr>
<tr><td>R8</td><td>brief: a script held forever leaves the hero black to 5.9 s · craft: loop ~70% dead black, lit left only, &lt;10% cool, page blacks ~7 levels short of red · system: PASS</td><td>head fetches the entrance's scripts and watches the bytes (2.5 s of nothing opens the page); second take tinted steel, glow, slate mids; BT.709 accurate rounding + sRGB transfer tag</td></tr>
<tr><td>R9</td><td>craft: orb rims crisp, light packed left, wordmark lighter than the side labels (inverted hierarchy) · brief: rate-limited</td><td>blur σ 26; the same take mirrored half a cycle on, tinted slate, lights the right; wordmark cut at 900 (1.38× the label's ink), recorded in the addendum</td></tr>
<tr><td>R10</td><td>craft: loop drifts at one speed as discs, a globe-on-stem reads as a lamp, a disc behind the left label; wordmark caps 14 px vs 19 · system: PASS</td><td>light streaked into planes; closed speed curve (4 → 20 → 5 a second); dark pools behind both flank labels. The wordmark size is the owner's call (15 letters in a 139 px block)</td></tr>
<tr><td>R10 brief</td><td>a script trickling in (not held) still leaves the page black to 5.9 s; 3G black ~4.7 s; static fallback on flat black</td><td>the head judges the download by its rate: no reply in 1.5 s or a projected finish &gt; 1.6 s after the page arrives opens the static hero, on its poster</td></tr>
<tr><td>R11</td><td>craft: the loop's rest fell on the reveal (dark and still), over-saturated, too clean</td><td>closed loop started 5 s in (mid-sweep), saturation to the reference's, light grain</td></tr>
<tr><td>R12</td><td>brief: PASS · craft: saturation drifts 0.28 → 0.48 through the loop; 5–9 scattered discs read as confetti</td><td>tighter crop, heavier blur (4–5 forms, one dominant); lit saturation capped at 0.40 (0.29–0.41 a second, reference 0.29–0.40)</td></tr>
<tr><td>R13</td><td>craft: loop reads as stock bokeh — uniform blur, round blobs drifting; wants focus that comes and goes and one-way sweeps; real letters show at the scramble's leading edge</td><td>every letter now seen decoding (0–3 of 116 by chance, was 40); new stills of copper and steel planes and arcs, animated with a focus pull and a sweep, first frame = last</td></tr>
<tr><td>R14</td><td>craft: torn edges (a hard threshold in the saturation cap), 70–81% flat navy, no warm light in seconds 3–7</td><td>soft cap, blur, low glow, amber second layer; wordmark stacked (owner's choice). Piece frozen here by the owner.</td></tr>
<tr><td>R15 (30.09, restarted)</td><td>owner: the front page sometimes sticks · bar sharpened with measured video rules 8–12 (the live site has since been redesigned; the saved 23 Sep copy stays the bar)</td><td>stuck: desk.js drew six sheets on load, a 1.09 s frame at 4.2 s — sheets now drawn on demand, bed too, page scripts wait for idle after the reveal: worst frame 66 ms, 12/12 loads clean. Video: sharp Higgsfield takes (Kling 3.0, A→B→A so the forms travel and the loop closes) + a Depth Anything depth map, blurred per pixel by depth with a focus plane that travels near → far → near (tools/node/hero-lens.py), glints kept, graded to rule 8. Hero v7 installed: focus held on the middle forms (the near glass lip never sharpens), depth dilated so rims don't halo sharp, blur floor σ 12, saturation capped at 0.42 — dark 63% · warm 7.0% · cool 6.5% · mean 26 · 15 levels/s · edges 0.39–0.90% · one glint 0.59% · seam below a normal frame step.</td></tr>
<tr><td>R15 verdicts</td><td>system PASS · brief FAIL: slow-4G phones froze the video 9× in 20 s (drawings and photos downloading alongside it; one 150–283 ms pages.js frame on a 4× slower CPU) · craft FAIL: a still-life of literal glass props wobbling in place, a 3.9% white flare</td><td>page scripts and photos now wait for the video to finish buffering (or a scroll/swipe/key; 30 s backstop); first render spread over five tasks; video capped at 820 kb/s. Slow 4G + 4× CPU: no stalls, no script frame over 50 ms</td></tr>
<tr><td>R16 (owner)</td><td>new Kling takes of glass columns tracking sideways, measured in range — the owner: "does not look like the website… it was light reflecting on water, almost. This is just something weird."</td><td>Round 17: tools/node/hero-water.py — five lights refracted through simulated rippling water (whole turns per loop, so it closes exactly), light splatted where the rays land (the caustic), smeared along travel, lens-like defocus with focus that comes and goes, one cream glint on the copper light at 2.5 s. Dark 68% · warm 6.3% · cool 5.0% · mean 23 · 14.3 levels/s · shadows (7, 12, 15) · 475 kb/s. Side-by-side: design/hero-compare.mp4</td></tr>
<tr><td>R17 verdicts</td><td>craft FAIL: "CG light ribbons — smoke or aurora", no softly focused form (edges ≈ 0%), no grain, no parallax, a full-height arc at the loop point · brief: entrance within 0.15 s of the reference ✓; loop "one or two smoke-like streaks over a lot of empty black" where theirs has five to eight overlapping faceted planes ✗; a 0.6–0.7 s freeze on a slow CPU at ~4.7 s ✗</td>
<td>freeze: the four viewers below the hero (3D room, walkthrough, plan, partition) now build only as they come within a screen of view — that step 76 ms → 0 ms at 4× CPU. Loop, two tries: faceted planes (hero-facets.py) read as slide-deck polygons; a Higgsfield photograph of defocused light through whisky, water and cut glass, set moving here (hero-still.py: copper and slate layers drifting apart, water ripple, focus drift, the cream highlight catching once a loop) — photographic, on the reference's numbers except pace (6.8 levels/s: the composition barely changes). Three-way: design/hero-compare-3.mp4. Next needs the owner: which direction, and Higgsfield credits for real moving footage</td></tr></table>`;
